---
- name: Deploy alert_smtp with debug mode
  hosts: nodes
  become: yes
  gather_facts: no

  tasks:
  - name: Copy the alert script to the nodes
    copy:
      src: alert_smtp.sh
      mode: 0750
      owner: hacluster
      group: haclient
      dest: /var/lib/pacemaker/alert_smtp_actual.sh   
     

  - name: copy the debug script to the nodes 
    copy:
      src: alert_smtp_debug.sh
      mode: 0750
      owner: hacluster
      group: haclient
      dest: /var/lib/pacemaker/alert_smtp.sh
