---
- name: Deploy alert_syslog
  hosts: nodes
  become: yes
  gather_facts: no

  tasks:
  - name: Copy the alert_smtp script to the nodes
    copy:
      src: alert_syslog.sh
      mode: 0750
      owner: hacluster
      group: haclient
      dest: /var/lib/pacemaker/alert_syslog.sh   
     

  - name: remove the debug alert_syslog script
    file:
      dest: /var/lib/pacemaker/alert_syslog.sh
      state: absent
